extern void delay_sec(unsigned int sec);
extern void delay_ms(unsigned int ms);
extern  void lcd_data(unsigned char data);
extern void lcd_cmd(unsigned int cmd);
extern void lcd_init(void);
extern void lcd_string(unsigned char *ptr);
typedef unsigned char u8;
typedef signed char s8;
typedef unsigned int u32;
typedef signed int s32;
extern void uart0_init(u32 baud);
extern void uart0_tx(u8 data);
extern unsigned char uart0_rx(void);
extern void uart0_tx_string(s8 *ptr);
extern short int adc_read(char ch);
extern void adc_init(void);
extern void uart0_tx_float(float f);
extern void uart0_tx_integer(int num);
extern void config_vic_for_uart0(void);
extern void en_uart0_interrupt(void);
extern void i2c_byte_write_frame(unsigned char sa,unsigned char mr,unsigned char data);
extern void i2c_init(void);
extern unsigned char i2c_byte_read_frame(unsigned char sa,unsigned mr);
extern void lcd_float(float f);
extern void adc_temp(void);
extern void light(void);
extern void spi0_init(void);
extern unsigned short int MCP3204_adc_read(char ch);
extern void lcd_integer(int num);
extern unsigned char spi0_data(unsigned char data);
